name: Publish

on:
  release:
    types: [released]

jobs:
  publish_to_pub_dev:
    name: Publish package to pub.dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Publish dry run
        run: flutter pub publish --dry-run
      
      - name: Publish to pub.dev
        if: github.event_name == 'release'
        run: |
          # Setup pub credentials
          mkdir -p $HOME/.config/dart
          echo '${{ secrets.PUB_DEV_CREDENTIALS }}' > $HOME/.config/dart/pub-credentials.json
          # Publish
          flutter pub publish --force